Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CRUD.DataBase;
using CRUD.Models;
using Microsoft.AspNetCore.Authorization;
using CRUD.ViewModel;
using AutoMapper;

namespace CRUD.Controllers
{
    [Authorize]
    public class ClienteController : Controller
    {
        private readonly ApplicationDBContext _context;
        private readonly IMapper _mapper;

        public ClienteController(ApplicationDBContext context, IMapper mapper)
        {
            _mapper = mapper;
            _context = context;
        }

        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? pageNumber)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NomeSortParm"] = String.IsNullOrEmpty(sortOrder) ? "nome_asc" : "nome_desc";
            ViewData["VendedorSortParm"] = String.IsNullOrEmpty(sortOrder) ? "vendedor_desc" : "";
            ViewData["TelefoneSortParm"] = sortOrder == "Tel" ? "tel_desc" : "Tel";
            ViewData["IDSortParm"] = sortOrder == "ID" ? "id_desc" : "ID";


            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            var clientes = from s in _context.Clientes.Include(c => c.Vendedor)
                          
                           select s;



            if (!String.IsNullOrEmpty(searchString))
            {
                clientes = clientes.Where(s => s.Nome.Contains(searchString) || s.Telefone.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "ID":
                    clientes = clientes.OrderBy(s => s.Id);
                    break;
                case "id_desc":
                    clientes = clientes.OrderByDescending(s => s.Id);
                    break;
                case "nome_desc":
                    clientes = clientes.OrderByDescending(s => s.Nome);
                    break;
                 case "nome_asc":
                    clientes = clientes.OrderBy(s => s.Nome);
                    break;
                case "vendedor_desc":
                    clientes = clientes.OrderByDescending(s => s.Vendedor.Nome);
                    break;
                 case "Tel":
                    clientes = clientes.OrderBy(s => s.Telefone);
                    break;
                case "tel_desc":
                    clientes = clientes.OrderByDescending(s => s.Telefone);
                    break;
                default:
                    clientes = clientes.OrderByDescending(s => s.Id);
                    break;
            }

            int pageSize = 5;

            return View(await PaginatedList<Cliente>.CreateAsync(clientes.AsNoTracking(), pageNumber ?? 1, pageSize));
        }

 
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes
                .Include(c => c.Vendedor)
                .Include(c => c.Produtos)
                .FirstOrDefaultAsync(m => m.Id == id);

            var c = _mapper.Map<Cliente, ClienteViewModel>(cliente);

            return View(c);
        }

       
        public IActionResult Create()
        {
            ViewData["VendedorID"] = new SelectList(_context.Vendedores, "Id", "Nome");
            return View();
        }

    
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ClienteViewModel cliente)
        {
            if (ModelState.IsValid)
            {
                var c = _mapper.Map<ClienteViewModel, Cliente>(cliente);
                _context.Add(c);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["VendedorID"] = new SelectList(_context.Vendedores, "Id", "Nome", cliente.VendedorID);
            return View(cliente);
        }

    
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes.FindAsync(id);
            var c = _mapper.Map<Cliente, ClienteViewModel>(cliente);
           
            ViewData["VendedorID"] = new SelectList(_context.Vendedores, "Id", "Nome", cliente.VendedorID);
            return View(c);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ClienteViewModel cliente)
        {
            if (id != cliente.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var c = _mapper.Map<ClienteViewModel, Cliente>(cliente);
                    _context.Update(c);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClienteExists(cliente.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["VendedorID"] = new SelectList(_context.Vendedores, "Id", "Nome", cliente.VendedorID);
            return View(cliente);
        }

       
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes
                .Include(c => c.Vendedor)
                .FirstOrDefaultAsync(m => m.Id == id);
            var c = _mapper.Map<Cliente, ClienteViewModel>(cliente);

            return View(c);
        }

        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cliente = await _context.Clientes.FindAsync(id);
            _context.Clientes.Remove(cliente);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClienteExists(int id)
        {
            return _context.Clientes.Any(e => e.Id == id);
        }
    }
}

Controllers/ProdutoController.cs
using AutoMapper;
using CRUD.DataBase;
using CRUD.Models;
using CRUD.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;

namespace CRUD.Controllers
{
    [Authorize]
    public class ProdutoController : Controller
    {
        private readonly ApplicationDBContext _context;
        private readonly IMapper _mapper;

        public ProdutoController(ApplicationDBContext context, IMapper mapper)
        {
            _mapper = mapper;
            _context = context;
        }

        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? pageNumber)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["ClienteSortParm"] = String.IsNullOrEmpty(sortOrder) ? "cliente_asc" : "cliente_desc";
            ViewData["DescricaoSortParm"] = String.IsNullOrEmpty(sortOrder) ? "descricao_asc" : "descricao_desc";
            ViewData["ValorSortParm"] = sortOrder == "Valor" ? "valor_desc" : "Valor";
            ViewData["IDSortParm"] = sortOrder == "ID" ? "id_desc" : "ID";
            ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";


            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            var produtos = from s in _context.Produtos.Include(p => p.Cliente)
                            select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                produtos = produtos.Where(s => s.Descricao.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "ID":
                    produtos = produtos.OrderBy(s => s.ID);
                    break;
                case "id_desc":
                    produtos = produtos.OrderByDescending(s => s.ID);
                    break;
                case "descricao_desc":
                    produtos = produtos.OrderByDescending(s => s.Descricao);
                    break;
                case "descricao_asc":
                    produtos = produtos.OrderBy(s => s.Descricao);
                    break;
                case "cliente_desc":
                    produtos = produtos.OrderByDescending(s => s.Cliente.Nome);
                    break;
                case "cliente_asc":
                    produtos = produtos.OrderBy(s => s.Cliente.Nome);
                    break;
                case "Valor":
                    produtos = produtos.OrderBy(s => s.Valor);
                    break;
                case "valor_desc":
                    produtos = produtos.OrderByDescending(s => s.Valor);
                    break;
                case "Date":
                    produtos = produtos.OrderBy(s => s.CriadoEm);
                    break;
                case "date_desc":
                    produtos = produtos.OrderByDescending(s => s.CriadoEm);
                    break;
                default:
                    produtos = produtos.OrderByDescending(s => s.ID);
                    break;
            }

            int pageSize = 5;

            return View(await PaginatedList<Produto>.CreateAsync(produtos.AsNoTracking(), pageNumber ?? 1, pageSize));
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produto = await _context.Produtos
                .Include(p => p.Cliente)
                .FirstOrDefaultAsync(m => m.ID == id);
            var p = _mapper.Map<Produto, ProdutoViewModel>(produto);

            if (produto == null)
            {
                return NotFound();
            }

            return View(p);
        }


        public IActionResult Create()
        {
            ViewData["ClienteID"] = new SelectList(_context.Clientes, "Id", "Nome");
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProdutoViewModel produto)
        {
            if (ModelState.IsValid)
            {
                var p = _mapper.Map<ProdutoViewModel, Produto>(produto); 

                p.CriadoEm = DateTime.Now;
                _context.Add(p);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClienteID"] = new SelectList(_context.Clientes, "Id", "Nome", produto.ClienteID);
            return View(produto);
        }


        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produto = await _context.Produtos.FindAsync(id);
            var p = _mapper.Map<Produto, ProdutoViewModel>(produto);

            ViewData["ClienteID"] = new SelectList(_context.Clientes, "Id", "Nome", produto.ClienteID);
            return View(p);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ProdutoViewModel produto)
        {
            if (id != produto.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var p = _mapper.Map<ProdutoViewModel, Produto>(produto);
                    _context.Update(p);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProdutoExists(produto.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClienteID"] = new SelectList(_context.Clientes, "Id", "Nome", produto.ClienteID);
            return View(produto);
        }


        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produto = await _context.Produtos
                .Include(p => p.Cliente)
                .FirstOrDefaultAsync(m => m.ID == id);

            var p = _mapper.Map<Produto, ProdutoViewModel>(produto);
          
            return View(p);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var produto = await _context.Produtos.FindAsync(id);
            _context.Produtos.Remove(produto);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProdutoExists(int id)
        {
            return _context.Produtos.Any(e => e.ID == id);
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager


<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Nutrimax</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="/plugins/fontawesome-free/css/all.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/dist/css/adminlte.min.css">
</head>
<body class="hold-transition sidebar-mini">
    <div class="wrapper">


        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link text-secondary" style="font-weight:bold;">Home</a>
                </li>
            </ul>

            @{ await Html.RenderPartialAsync("_LoginPartial.cshtml"); }

        </nav>


        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a asp-area="" asp-controller="Home" asp-action="Index" class="brand-link">
                <span class="ml-2 font-weight-bold text-white">Nutrimax</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar mt-2">
                <!-- Sidebar user panel (optional) -->
                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
    with font-awesome or any other icon font library -->
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Vendedor" asp-action="Index">
                                Representantes <i class="ml-1 fa fa-briefcase"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Cliente" asp-action="Index">
                                Clientes <i class="ml-1 fa fa-users"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Produto" asp-action="Index">
                                Produtos <i class="ml-1 fa fa-cart-plus"></i>
                            </a>
                        </li>


                            <li class="nav-item">
                                <a class="nav-link" id="register" asp-area="Identity" asp-page="/Account/Register">
                                    Cadastrar usuário <i class="ml-1 fa  fa-plus"></i>
                                </a>
                            </li>
                        
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <!-- /.content-header -->
            <!-- Main content -->
            <div class="content ml-5 mr-5">
                @RenderBody()
            </div>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
            <div class="p-3">
                <h5>Title</h5>
                <p>Sidebar content</p>
            </div>
        </aside>
        <!-- /.control-sidebar -->
        <!-- Main Footer -->
        <footer class="main-footer">
            <p>Copyright &copy;</p>
        </footer>
    </div>
    <!-- ./wrapper -->
    <!-- REQUIRED SCRIPTS -->
    <!-- jQuery -->
    <script src="/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="/dist/js/adminlte.min.js"></script>
</body>
</html>

@RenderSection("Scripts", required: false)